# -*- coding: utf-8 -*-
"""XOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q_AUYe-v4aSZL8uitKFNonflZW1QAGcM
"""

from sklearn.neural_network import MLPClassifier

X = [[0., 0.],[0.,1.],[1.,0.],[1.,1.]]

Y = [0,1,1,0]

clf = MLPClassifier(hidden_layer_sizes = (2), activation = 'logistic', solver = 'lbfgs')

clf.fit(X,Y)

clf.predict(X)

clf.coefs_[0]

clf.coefs_[1]

clf.intercepts_[0]



